### ISSUE TITLE
Problem with lexical scoping in declaration list

### ISSUE THREAD

**Issue by vijunag** [eliben/pycparser#118]
An ID in the local scope(which can shadow a TYPEID in higher scope) is being recognized as a TYPEID which is already defined at a higher scope level and this happens only in a declaration list. 

Consider this example
Case 1: The type_lookup_func recognizes the second variable "a" as an already defined TYPEID and crashes. 

```
src="""
    typedef int a;
    int main()
    {
        int a,b;
    }
""
```

```
>
  File "/home/vijay/script/pycparser/pycparser/c_parser.py", line 1705, in p_error
    column=self.clex.find_tok_column(p)))
  File "/home/vijay/script/pycparser/pycparser/plyparser.py", line 55, in _parse_error
    raise ParseError("%s: %s" % (coord, msg))
pycparser.plyparser.ParseError: :5:14: before: ,
```

Case 2: However the below example works just fine

```
src="""
typedef int a;
int main(void)
{
int a;
int b;
}
p.parse(src).show()
```

```
FileAST:
  Typedef: a, [], ['typedef']
    TypeDecl: a, []
      IdentifierType: ['int']
  FuncDef:
    Decl: main, [], [], []
      FuncDecl:
        TypeDecl: main, []
          IdentifierType: ['int']
    Compound:
      Decl: a, [], [], []
        TypeDecl: a, []
          IdentifierType: ['int']
      Decl: b, [], [], []
        TypeDecl: b, []
          IdentifierType: ['int']
```
