### ISSUE TITLE
Pragma in for loop without compound statement

### ISSUE THREAD

**Issue by were** [eliben/pycparser#248]
````````
int i;
for (i = 0; i < 10; ++i)
  #pragma something
  a[i]=i;
````````
It regards `#pragma` as a statement and `a[i]=i` is a statementment at the same level with the for loop.
However semantically, it should be a compound statement.

**Comment by eliben** [comment]
Wasn't this addressed here: https://github.com/eliben/pycparser/commit/7af2fb909b7cf4ee7cb1dd37bbe08d7e10f41349

?

**Comment by were** [comment]
I double checked. At least it is not addressed under v2.18.
Here is the Python code uses this repo:
``````
#!/usr/bin/env python3

import pycparser, sys
print(pycparser.__version__)
parser = pycparser.c_parser.CParser()
ast = parser.parse(
r"""
int main() {
  int a;
  int i;

  for (i = 0; i < 5; ++i)
#pragma something
    a = i;

  return 0;
}
""")

print(ast.show())
``````
Here is the output:
``````
2.18
FileAST: 
  FuncDef: 
    Decl: main, [], [], []
      FuncDecl: 
        TypeDecl: main, []
          IdentifierType: ['int']
    Compound: 
      Decl: a, [], [], []
        TypeDecl: a, []
          IdentifierType: ['int']
      Decl: i, [], [], []
        TypeDecl: i, []
          IdentifierType: ['int']
      For: 
        Assignment: =
          ID: i
          Constant: int, 0
        BinaryOp: <
          ID: i
          Constant: int, 5
        UnaryOp: ++
          ID: i
        Pragma: something
      Assignment: =
        ID: a
        ID: i
      Return: 
        Constant: int, 0
None
``````
I hope this issue can be replicated easily with the information above.
Thanks.
