### ISSUE TITLE
Different ASTs from codes the same in meaning

### ISSUE THREAD

**Issue by akiradeveloper** [eliben/pycparser#52]
Hi,

The AST for t1 and t2 produces different ASTs which really bugs me now. My code assumes the parent of a Return node is always Compound. However, in t1, it is not.

Should we fix this? or is this your intention?

If this is your intention, I will write workaround to rewrite all if, while and for as to form link in t2. Please tell me if caring only these three is not sufficient.

``` python
rom pycparser import c_parser

t1 = r"""
int f()
{
        if (0)
                return 0;

        while (0)
                return 0;

        for (;;)
                return 0;
}
"""

t2 = r"""
int f()
{
        if (0) {
                return 0;
        }

        while (0) {
                return 0;
        }

        for (;;) {
                return 0;
        }
}
"""

def parse(t):
        parser = c_parser.CParser()
        parser.parse(t).show()

parse(t1)
parse(t2)
```

OUTPUT:

```
FileAST:
  FuncDef:
    Decl: f, [], [], []
      FuncDecl:
        TypeDecl: f, []
          IdentifierType: ['int']
    Compound:
      If:
        Constant: int, 0
        Return:
          Constant: int, 0
      While:
        Constant: int, 0
        Return:
          Constant: int, 0
      For:
        Return:
          Constant: int, 0
FileAST:
  FuncDef:
    Decl: f, [], [], []
      FuncDecl:
        TypeDecl: f, []
          IdentifierType: ['int']
    Compound:
      If:
        Constant: int, 0
        Compound:
          Return:
            Constant: int, 0
      While:
        Constant: int, 0
        Compound:
          Return:
            Constant: int, 0
      For:
        Compound:
          Return:
            Constant: int, 0
```
