### ISSUE TITLE
Incorrect Parsing of Hexadecimal Floating Point Literals

### ISSUE THREAD

**Issue by graypinkfurball** [eliben/pycparser#556]
I noticed that code ignores type suffixes on hexadecimal floating point literals.
[c_parser.py#L1882](https://github.com/eliben/pycparser/c_parser.py#L1882)

The code was introduced in [this commit](https://github.com/eliben/pycparser/commit/a915c3d) explicitly ignoring hexadecimal literals, and [this commit](https://github.com/eliben/pycparser/commit/40f0d91) added an incorrect test.

```C
float a = 0xDE.38p0;
```
```
FileAST:
  Decl: a, [], [], [], []
    TypeDecl: a, [], None
      IdentifierType: ['float']
    Constant: float, 0xDE.38p0
```
The `type` of the constant should be "double" by default, and affected by type suffixes.

---

I ran a little test with my compiler to verify the sizes of the literals.
```C
#include <stdio.h>
int main(void) {
  printf("%llu %llu %llu",
    sizeof(0xDE.38p0f),
    sizeof(0xDE.38p0),
    sizeof(0xDE.38p0l));
  return 0;
}
```
```
4 8 16
```
